fix convert support china
cryptape/appchainj pull request #170
Opened 2020-04-07 03:40 UTC by UDLD

2020-04-08 07:32 UTC, rainchen commented on protobuf/src/main/java/com/citahub/cita/protobuf/ConvertStrByte.java
> +             i < bs.length; i++) {
why break into 2 lines?

2020-04-08 07:34 UTC, rainchen commented on protobuf/src/main/java/com/citahub/cita/protobuf/ConvertStrByte.java
> -        StringBuffer hexString = new StringBuffer();
do we have a test case for this change?

2020-04-08 07:35 UTC, rainchen requested changes
commented

2020-04-08 07:47 UTC, UDLD commented on protobuf/src/main/java/com/citahub/cita/protobuf/ConvertStrByte.java
> -        StringBuffer hexString = new StringBuffer();
@rainchen  yes, more test in old cases

2020-04-08 07:47 UTC, UDLD commented on protobuf/src/main/java/com/citahub/cita/protobuf/ConvertStrByte.java
> +             i < bs.length; i++) {
fixed

2020-04-09 02:16 UTC, UDLD commented
@rainchen  add chinese case done

2020-04-09 15:32 UTC, UDLD commented on protobuf/src/main/java/com/citahub/cita/protobuf/ConvertStrByte.java
> -        StringBuffer hexString = new StringBuffer();
> do we have a test case for this change?

fixed

2020-04-10 01:48 UTC, rainchen approved these changes

2020-04-10 02:24 UTC, yangzhenlong approved these changes
the title `china` should be `chinese`

2020-04-10 02:25 UTC, merged